// Code generated by protoc-gen-go. DO NOT EDIT.
// source: photos/events/pb/photos.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhotoUploaded struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoUploaded) Reset()         { *m = PhotoUploaded{} }
func (m *PhotoUploaded) String() string { return proto.CompactTextString(m) }
func (*PhotoUploaded) ProtoMessage()    {}
func (*PhotoUploaded) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{0}
}

func (m *PhotoUploaded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoUploaded.Unmarshal(m, b)
}
func (m *PhotoUploaded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoUploaded.Marshal(b, m, deterministic)
}
func (m *PhotoUploaded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoUploaded.Merge(m, src)
}
func (m *PhotoUploaded) XXX_Size() int {
	return xxx_messageInfo_PhotoUploaded.Size(m)
}
func (m *PhotoUploaded) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoUploaded.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoUploaded proto.InternalMessageInfo

func (m *PhotoUploaded) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PhotoRearrange struct {
	AlbumId              string   `protobuf:"bytes,1,opt,name=albumId,proto3" json:"albumId,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	After                string   `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoRearrange) Reset()         { *m = PhotoRearrange{} }
func (m *PhotoRearrange) String() string { return proto.CompactTextString(m) }
func (*PhotoRearrange) ProtoMessage()    {}
func (*PhotoRearrange) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{1}
}

func (m *PhotoRearrange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoRearrange.Unmarshal(m, b)
}
func (m *PhotoRearrange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoRearrange.Marshal(b, m, deterministic)
}
func (m *PhotoRearrange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoRearrange.Merge(m, src)
}
func (m *PhotoRearrange) XXX_Size() int {
	return xxx_messageInfo_PhotoRearrange.Size(m)
}
func (m *PhotoRearrange) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoRearrange.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoRearrange proto.InternalMessageInfo

func (m *PhotoRearrange) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

func (m *PhotoRearrange) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PhotoRearrange) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type PhotoDelete struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoDelete) Reset()         { *m = PhotoDelete{} }
func (m *PhotoDelete) String() string { return proto.CompactTextString(m) }
func (*PhotoDelete) ProtoMessage()    {}
func (*PhotoDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{2}
}

func (m *PhotoDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoDelete.Unmarshal(m, b)
}
func (m *PhotoDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoDelete.Marshal(b, m, deterministic)
}
func (m *PhotoDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoDelete.Merge(m, src)
}
func (m *PhotoDelete) XXX_Size() int {
	return xxx_messageInfo_PhotoDelete.Size(m)
}
func (m *PhotoDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoDelete.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoDelete proto.InternalMessageInfo

func (m *PhotoDelete) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type AlbumRemovePhoto struct {
	AlbumId              string   `protobuf:"bytes,1,opt,name=albumId,proto3" json:"albumId,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlbumRemovePhoto) Reset()         { *m = AlbumRemovePhoto{} }
func (m *AlbumRemovePhoto) String() string { return proto.CompactTextString(m) }
func (*AlbumRemovePhoto) ProtoMessage()    {}
func (*AlbumRemovePhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{3}
}

func (m *AlbumRemovePhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumRemovePhoto.Unmarshal(m, b)
}
func (m *AlbumRemovePhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumRemovePhoto.Marshal(b, m, deterministic)
}
func (m *AlbumRemovePhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumRemovePhoto.Merge(m, src)
}
func (m *AlbumRemovePhoto) XXX_Size() int {
	return xxx_messageInfo_AlbumRemovePhoto.Size(m)
}
func (m *AlbumRemovePhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumRemovePhoto.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumRemovePhoto proto.InternalMessageInfo

func (m *AlbumRemovePhoto) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

func (m *AlbumRemovePhoto) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type AlbumCreate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlbumCreate) Reset()         { *m = AlbumCreate{} }
func (m *AlbumCreate) String() string { return proto.CompactTextString(m) }
func (*AlbumCreate) ProtoMessage()    {}
func (*AlbumCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{4}
}

func (m *AlbumCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumCreate.Unmarshal(m, b)
}
func (m *AlbumCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumCreate.Marshal(b, m, deterministic)
}
func (m *AlbumCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumCreate.Merge(m, src)
}
func (m *AlbumCreate) XXX_Size() int {
	return xxx_messageInfo_AlbumCreate.Size(m)
}
func (m *AlbumCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumCreate.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumCreate proto.InternalMessageInfo

func (m *AlbumCreate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AlbumCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AlbumRename struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlbumRename) Reset()         { *m = AlbumRename{} }
func (m *AlbumRename) String() string { return proto.CompactTextString(m) }
func (*AlbumRename) ProtoMessage()    {}
func (*AlbumRename) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{5}
}

func (m *AlbumRename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumRename.Unmarshal(m, b)
}
func (m *AlbumRename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumRename.Marshal(b, m, deterministic)
}
func (m *AlbumRename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumRename.Merge(m, src)
}
func (m *AlbumRename) XXX_Size() int {
	return xxx_messageInfo_AlbumRename.Size(m)
}
func (m *AlbumRename) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumRename.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumRename proto.InternalMessageInfo

func (m *AlbumRename) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AlbumRename) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type AlbumAddPhoto struct {
	AlbumId              string   `protobuf:"bytes,1,opt,name=albumId,proto3" json:"albumId,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	After                string   `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlbumAddPhoto) Reset()         { *m = AlbumAddPhoto{} }
func (m *AlbumAddPhoto) String() string { return proto.CompactTextString(m) }
func (*AlbumAddPhoto) ProtoMessage()    {}
func (*AlbumAddPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9b914788f4b29d, []int{6}
}

func (m *AlbumAddPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumAddPhoto.Unmarshal(m, b)
}
func (m *AlbumAddPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumAddPhoto.Marshal(b, m, deterministic)
}
func (m *AlbumAddPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumAddPhoto.Merge(m, src)
}
func (m *AlbumAddPhoto) XXX_Size() int {
	return xxx_messageInfo_AlbumAddPhoto.Size(m)
}
func (m *AlbumAddPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumAddPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumAddPhoto proto.InternalMessageInfo

func (m *AlbumAddPhoto) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

func (m *AlbumAddPhoto) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AlbumAddPhoto) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func init() {
	proto.RegisterType((*PhotoUploaded)(nil), "PhotoUploaded")
	proto.RegisterType((*PhotoRearrange)(nil), "PhotoRearrange")
	proto.RegisterType((*PhotoDelete)(nil), "PhotoDelete")
	proto.RegisterType((*AlbumRemovePhoto)(nil), "AlbumRemovePhoto")
	proto.RegisterType((*AlbumCreate)(nil), "AlbumCreate")
	proto.RegisterType((*AlbumRename)(nil), "AlbumRename")
	proto.RegisterType((*AlbumAddPhoto)(nil), "AlbumAddPhoto")
}

func init() { proto.RegisterFile("photos/events/pb/photos.proto", fileDescriptor_2a9b914788f4b29d) }

var fileDescriptor_2a9b914788f4b29d = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0x50, 0xa8, 0xb8, 0xaa, 0x15, 0xb2, 0x18, 0xb2, 0x20, 0x81, 0x59, 0x98, 0x88,
	0x10, 0x03, 0x2b, 0x05, 0x16, 0x16, 0x84, 0x02, 0x2c, 0x6c, 0x17, 0xf9, 0x41, 0x2b, 0x25, 0xb6,
	0xe5, 0x9a, 0xf2, 0xf7, 0x91, 0xaf, 0x35, 0x1d, 0xc8, 0x42, 0xb7, 0xfb, 0x4e, 0xef, 0x7b, 0x17,
	0xc5, 0x74, 0xe2, 0xe7, 0x2e, 0xba, 0x65, 0x85, 0x15, 0x6c, 0x5c, 0x56, 0xbe, 0xa9, 0xd6, 0x8b,
	0x4b, 0x1f, 0x5c, 0x74, 0xfa, 0x9c, 0x26, 0xcf, 0x89, 0xdf, 0x7c, 0xeb, 0xd8, 0xc0, 0x28, 0x45,
	0x43, 0xcf, 0x71, 0x5e, 0x0e, 0x4e, 0x07, 0x17, 0x87, 0xb5, 0xcc, 0xfa, 0x95, 0xa6, 0x12, 0xaa,
	0xc1, 0x21, 0xb0, 0xfd, 0x84, 0x2a, 0x69, 0xc4, 0x6d, 0xf3, 0xd5, 0x3d, 0x9a, 0x4d, 0x30, 0xe3,
	0xaf, 0x5f, 0x6c, 0x7d, 0x75, 0x4c, 0xfb, 0xfc, 0x11, 0x11, 0xca, 0x3d, 0x59, 0xae, 0x41, 0x9f,
	0xd1, 0x58, 0x5a, 0x1f, 0xd0, 0x22, 0xa2, 0xf7, 0xf0, 0x2d, 0x1d, 0xcd, 0x52, 0x6f, 0x8d, 0xce,
	0xad, 0x20, 0xe9, 0xff, 0x9d, 0xd6, 0x57, 0x34, 0x96, 0x86, 0xfb, 0x00, 0x8e, 0x50, 0x53, 0x2a,
	0x16, 0xd9, 0x2b, 0x16, 0xa2, 0x58, 0xee, 0x90, 0x95, 0x34, 0xeb, 0x9b, 0x8d, 0x52, 0x23, 0xe1,
	0x1f, 0xa5, 0xa4, 0x91, 0xc5, 0xf7, 0xd3, 0xd6, 0xca, 0xa8, 0x5f, 0x68, 0x22, 0xe2, 0xcc, 0x98,
	0x1d, 0x3e, 0xb5, 0xff, 0x2f, 0xdd, 0x0d, 0xdf, 0x0b, 0xdf, 0x34, 0x07, 0xf2, 0x5a, 0xd7, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xeb, 0xa3, 0xa8, 0xce, 0x01, 0x00, 0x00,
}
