// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam/pb/protos.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommentCreate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentCreate) Reset()         { *m = CommentCreate{} }
func (m *CommentCreate) String() string { return proto.CompactTextString(m) }
func (*CommentCreate) ProtoMessage()    {}
func (*CommentCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa5785c4ebdaebb, []int{0}
}

func (m *CommentCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentCreate.Unmarshal(m, b)
}
func (m *CommentCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentCreate.Marshal(b, m, deterministic)
}
func (m *CommentCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentCreate.Merge(m, src)
}
func (m *CommentCreate) XXX_Size() int {
	return xxx_messageInfo_CommentCreate.Size(m)
}
func (m *CommentCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentCreate.DiscardUnknown(m)
}

var xxx_messageInfo_CommentCreate proto.InternalMessageInfo

func (m *CommentCreate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommentCreate) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CommentCreate) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CommentCreate) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CommentUpdate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewMessage           string   `protobuf:"bytes,2,opt,name=newMessage,proto3" json:"newMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentUpdate) Reset()         { *m = CommentUpdate{} }
func (m *CommentUpdate) String() string { return proto.CompactTextString(m) }
func (*CommentUpdate) ProtoMessage()    {}
func (*CommentUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa5785c4ebdaebb, []int{1}
}

func (m *CommentUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentUpdate.Unmarshal(m, b)
}
func (m *CommentUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentUpdate.Marshal(b, m, deterministic)
}
func (m *CommentUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentUpdate.Merge(m, src)
}
func (m *CommentUpdate) XXX_Size() int {
	return xxx_messageInfo_CommentUpdate.Size(m)
}
func (m *CommentUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CommentUpdate proto.InternalMessageInfo

func (m *CommentUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommentUpdate) GetNewMessage() string {
	if m != nil {
		return m.NewMessage
	}
	return ""
}

type CommentDelete struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentDelete) Reset()         { *m = CommentDelete{} }
func (m *CommentDelete) String() string { return proto.CompactTextString(m) }
func (*CommentDelete) ProtoMessage()    {}
func (*CommentDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa5785c4ebdaebb, []int{2}
}

func (m *CommentDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentDelete.Unmarshal(m, b)
}
func (m *CommentDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentDelete.Marshal(b, m, deterministic)
}
func (m *CommentDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentDelete.Merge(m, src)
}
func (m *CommentDelete) XXX_Size() int {
	return xxx_messageInfo_CommentDelete.Size(m)
}
func (m *CommentDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentDelete.DiscardUnknown(m)
}

var xxx_messageInfo_CommentDelete proto.InternalMessageInfo

func (m *CommentDelete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CommentCreate)(nil), "CommentCreate")
	proto.RegisterType((*CommentUpdate)(nil), "CommentUpdate")
	proto.RegisterType((*CommentDelete)(nil), "CommentDelete")
}

func init() { proto.RegisterFile("iam/pb/protos.proto", fileDescriptor_aaa5785c4ebdaebb) }

var fileDescriptor_aaa5785c4ebdaebb = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x4c, 0xcc, 0xd5,
	0x2f, 0x48, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x03, 0x53, 0x4a, 0xd9, 0x5c, 0xbc,
	0xce, 0xf9, 0xb9, 0xb9, 0xa9, 0x79, 0x25, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x42, 0x7c, 0x5c,
	0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x12, 0x5c,
	0xec, 0xc5, 0xa5, 0x49, 0x59, 0xa9, 0xc9, 0x25, 0x12, 0x4c, 0x60, 0x41, 0x18, 0x57, 0x48, 0x8c,
	0x8b, 0xad, 0xb4, 0x38, 0xb5, 0xc8, 0x33, 0x45, 0x82, 0x19, 0x2c, 0x01, 0xe5, 0x81, 0x74, 0xe4,
	0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x4a, 0xb0, 0x40, 0x74, 0x40, 0xb9, 0x4a, 0xf6, 0x70, 0xcb,
	0x42, 0x0b, 0x52, 0xb0, 0x59, 0x26, 0xc7, 0xc5, 0x95, 0x97, 0x5a, 0xee, 0x0b, 0xd5, 0x0d, 0xb1,
	0x0f, 0x49, 0x44, 0x49, 0x1e, 0x6e, 0x80, 0x4b, 0x6a, 0x4e, 0x2a, 0xa6, 0x01, 0x4e, 0x2c, 0x51,
	0x4c, 0x05, 0x49, 0x49, 0x6c, 0x60, 0xbf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xa8,
	0xec, 0x68, 0xf2, 0x00, 0x00, 0x00,
}
