// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat/pb/protos.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCreate struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Admin                bool     `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreate) Reset()         { *m = UserCreate{} }
func (m *UserCreate) String() string { return proto.CompactTextString(m) }
func (*UserCreate) ProtoMessage()    {}
func (*UserCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_753ac9fd3f03caeb, []int{0}
}

func (m *UserCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreate.Unmarshal(m, b)
}
func (m *UserCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreate.Marshal(b, m, deterministic)
}
func (m *UserCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreate.Merge(m, src)
}
func (m *UserCreate) XXX_Size() int {
	return xxx_messageInfo_UserCreate.Size(m)
}
func (m *UserCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreate.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreate proto.InternalMessageInfo

func (m *UserCreate) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCreate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserCreate) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type UserSetName struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSetName) Reset()         { *m = UserSetName{} }
func (m *UserSetName) String() string { return proto.CompactTextString(m) }
func (*UserSetName) ProtoMessage()    {}
func (*UserSetName) Descriptor() ([]byte, []int) {
	return fileDescriptor_753ac9fd3f03caeb, []int{1}
}

func (m *UserSetName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSetName.Unmarshal(m, b)
}
func (m *UserSetName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSetName.Marshal(b, m, deterministic)
}
func (m *UserSetName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSetName.Merge(m, src)
}
func (m *UserSetName) XXX_Size() int {
	return xxx_messageInfo_UserSetName.Size(m)
}
func (m *UserSetName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSetName.DiscardUnknown(m)
}

var xxx_messageInfo_UserSetName proto.InternalMessageInfo

func (m *UserSetName) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserSetName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserPromote struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPromote) Reset()         { *m = UserPromote{} }
func (m *UserPromote) String() string { return proto.CompactTextString(m) }
func (*UserPromote) ProtoMessage()    {}
func (*UserPromote) Descriptor() ([]byte, []int) {
	return fileDescriptor_753ac9fd3f03caeb, []int{2}
}

func (m *UserPromote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPromote.Unmarshal(m, b)
}
func (m *UserPromote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPromote.Marshal(b, m, deterministic)
}
func (m *UserPromote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPromote.Merge(m, src)
}
func (m *UserPromote) XXX_Size() int {
	return xxx_messageInfo_UserPromote.Size(m)
}
func (m *UserPromote) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPromote.DiscardUnknown(m)
}

var xxx_messageInfo_UserPromote proto.InternalMessageInfo

func (m *UserPromote) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserDemote struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDemote) Reset()         { *m = UserDemote{} }
func (m *UserDemote) String() string { return proto.CompactTextString(m) }
func (*UserDemote) ProtoMessage()    {}
func (*UserDemote) Descriptor() ([]byte, []int) {
	return fileDescriptor_753ac9fd3f03caeb, []int{3}
}

func (m *UserDemote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDemote.Unmarshal(m, b)
}
func (m *UserDemote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDemote.Marshal(b, m, deterministic)
}
func (m *UserDemote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDemote.Merge(m, src)
}
func (m *UserDemote) XXX_Size() int {
	return xxx_messageInfo_UserDemote.Size(m)
}
func (m *UserDemote) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDemote.DiscardUnknown(m)
}

var xxx_messageInfo_UserDemote proto.InternalMessageInfo

func (m *UserDemote) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCreate)(nil), "UserCreate")
	proto.RegisterType((*UserSetName)(nil), "UserSetName")
	proto.RegisterType((*UserPromote)(nil), "UserPromote")
	proto.RegisterType((*UserDemote)(nil), "UserDemote")
}

func init() { proto.RegisterFile("chat/pb/protos.proto", fileDescriptor_753ac9fd3f03caeb) }

var fileDescriptor_753ac9fd3f03caeb = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0x48, 0x2c,
	0xd1, 0x2f, 0x48, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x03, 0x53, 0x4a, 0x1e, 0x5c,
	0x5c, 0xa1, 0xc5, 0xa9, 0x45, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0xa9,
	0xb9, 0x89, 0x99, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x10, 0x1f, 0x17,
	0x53, 0x66, 0x8a, 0x04, 0x13, 0x58, 0x88, 0x29, 0x33, 0x05, 0xa4, 0x2a, 0x31, 0x25, 0x37, 0x33,
	0x4f, 0x82, 0x59, 0x81, 0x51, 0x83, 0x23, 0x08, 0xc2, 0x51, 0x32, 0xe4, 0xe2, 0x06, 0x99, 0x14,
	0x9c, 0x5a, 0xe2, 0x97, 0x98, 0x9b, 0x0a, 0xd5, 0xc4, 0x08, 0xd7, 0x24, 0xc4, 0xc5, 0x92, 0x97,
	0x98, 0x9b, 0x0a, 0x35, 0x06, 0xcc, 0x56, 0x92, 0x85, 0x68, 0x09, 0x28, 0xca, 0xcf, 0xcd, 0x2f,
	0xc1, 0xd0, 0xa2, 0x24, 0x03, 0x71, 0x9b, 0x4b, 0x2a, 0x36, 0x59, 0x27, 0x96, 0x28, 0xa6, 0x82,
	0xa4, 0x24, 0x36, 0xb0, 0x37, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0xde, 0x21, 0x12,
	0xde, 0x00, 0x00, 0x00,
}
